### ISSUE TITLE
Change Font Family

### ISSUE THREAD

**Issue by timbacon** [palerdot/react-d3-speedometer#106]
Is there a way to change the font family of the labels and value text?

**Comment by palerdot** [comment]
Please use regular css to target the labels and value text for overriding the default font family. If you inspect the speedometer, you will see each dom element will have a distinct `class name`. Please use that to target the elements ... something like 
```javascript
#my-speedometer .segment-label {
  font-family: 'MyFamily'
}
```

Please reopen if you still have trouble doing this. Or better share a codesandbox ...
