### ISSUE TITLE
Is there a way to use a logarithmic scale instead of the linear one ? 

### ISSUE THREAD

**Issue by Flowtter** [palerdot/react-d3-speedometer#112]
Hi,
I was wondering if there was a way to use a logarithmic scale instead of the linear one?
Thanks

**Comment by palerdot** [comment]
You can use `customSegmentStops` to create stops at your preferred value like 
```
<ReactSpeedometer
    customSegmentStops={[0, 500, 750, 900, 1000]}
    segmentColors={["firebrick", "tomato", "gold", "limegreen"]}
    value={333}
  />
```
You can see it in example here - https://palerdot.in/react-d3-speedometer/?path=/story/reactspeedometer--custom-segment-stops.

Basically, you need to calculate the logarithmic values and create custom segment stops out of them.

Please reopen the issue if you still find this not appropriate for your use case.
