### ISSUE TITLE
Custom formatting of values

### ISSUE THREAD

**Issue by mohammadnouritani** [palerdot/react-d3-speedometer#113]
can we change the needle SVG is it possible to do that 

also can we custom the label of the numbers 

can we show the numbers with the custom label for segments

**Comment by palerdot** [comment]
> can we change the needle SVG is it possible to do that

This is not possible right now. 

> also can we custom the label of the numbers

This should be possible with `valueFormat` prop.

> can we show the numbers with the custom label for segments

Please share a screenshot or more info on this since I could not understand what you mean by this

**Comment by mohammadnouritani** [comment]
![image](https://user-images.githubusercontent.com/55382002/113968821-b8965980-97e8-11eb-9e01-3e0cc9f7d591.png)

I want to change the 1400 and the 1700 to say " min 1400" , "max 1700"



in this image I am using the custom segments labels 
![image](https://user-images.githubusercontent.com/55382002/113969128-42debd80-97e9-11eb-8ef6-7753e1cdb019.png)

you can see that the numbers are gone 

can I show both the number and the segment labels

**Comment by palerdot** [comment]
> can I show both the number and the segment labels

No. It is not possible right now.

PRs are welcome

**Comment by palerdot** [comment]
I think this could be achieved by passing a `formatValue` function which allows the user to customise how the values are formatted ... something like 
```
<ReactSpeedometer 
   formatValue={value => {
      if (value === "1400") { return "min $1400" }
   }}
/>
```

In any case, right now this feature is not available. I will see if this can be achieved in future releases.

**Comment by palerdot** [comment]
@mohammadnouritani I'm reopening this issue so that issue can be worked on in future. Thanks for raising this issue.

**Comment by mohammadnouritani** [comment]
> I think this could be achieved by passing a `formatValue` function prop (which is not available now) which allows the user to customise how the values are formatted ... something like
> 
> ```
> <ReactSpeedometer 
>    formatValue={value => {
>       if (value === "1400") { return "min $1400" }
>    }}
> />
> ```
> 
> In any case, right now this feature is not available. I will see if this can be achieved in future releases.

This will change the value in the label bellow I want to change the numbers with value formate array for each segment divider

**Comment by palerdot** [comment]
> This will change the value in the label bellow I want to change the numbers with value formate array for each segment divider

can you elaborate more with an example?

**Comment by nilesh1762** [comment]
I want to show % with vale. How can I do with gradient color.

**Comment by palerdot** [comment]
> I want to show % with vale. How can I do with gradient color.

can you elaborate more with an example?

**Comment by nilesh1762** [comment]
> > I want to show % with vale. How can I do with gradient color.
> 
> can you elaborate more with an example?
![Gauge_with_trend](https://user-images.githubusercontent.com/41782339/133737945-33d3c953-d072-4f83-885c-5bd4e4fc70b2.png)


I mean I want to show value which is connect with spedometer graph with % sign. I have attach snap.You will see every value there is % sign is attached.But I have to do this with css gradient.

**Comment by nilesh1762** [comment]
> > > I want to show % with vale. How can I do with gradient color.
> > 
> > 
> > can you elaborate more with an example?
> > ![Gauge_with_trend](https://user-images.githubusercontent.com/41782339/133737945-33d3c953-d072-4f83-885c-5bd4e4fc70b2.png)
> 
> I mean I want to show value which is connect with spedometer graph with % sign. I have attach snap.You will see every value there is % sign is attached.But I have to do this with css gradient.

I have make same as given snap with gradient effect,

**Comment by palerdot** [comment]
You can use `customSegmentLabels` for having more control over colors and display text - https://palerdot.in/react-d3-speedometer/?path=/story/reactspeedometer--custom-segment-labels. In this case, you have to calculate the values for display so that you can use appropriate formatting.

Example sandbox - https://codesandbox.io/s/condescending-lewin-v2vty?file=/src/App.js

**Comment by muhammadnaved** [comment]
@palerdot How can I add the Target needle which is shown in the below snapshot? Do we have any prop?
Could you please help I am new to React?
<img width="505" alt="image" src="https://user-images.githubusercontent.com/18066463/216685155-c7052c7f-e8ce-477b-b093-386341f04125.png">

**Comment by palerdot** [comment]
Custom formatting of values is now available `viaFormatter` prop - https://github.com/palerdot/react-d3-speedometer/issues/152

Closing this issue.

**Comment by palerdot** [comment]
@mohammadnouritani 
This option/prop is not available and also not planned.

For future updates use this issue - https://github.com/palerdot/react-d3-speedometer/issues/163

> @palerdot How can I add the Target needle which is shown in the below snapshot? Do we have any prop? Could you please help I am new to React? <img alt="image" width="505" src="https://user-images.githubusercontent.com/18066463/216685155-c7052c7f-e8ce-477b-b093-386341f04125.png">
