### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajits731** [palerdot/react-d3-speedometer#12]
Why this error is popping up? I'm trying the simplest form.

./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in D:\mike\node_modules\xmlhttprequest\lib
resolve module child_process in D:\mike\node_modules\xmlhttprequest\lib
  looking for modules in D:\mike\node_modules
    D:\mike\node_modules\child_process doesn't exist (module as directory)
    resolve 'file' child_process in D:\mike\node_modules
      resolve file
        D:\mike\node_modules\child_process doesn't exist
        D:\mike\node_modules\child_process.js doesn't exist
        D:\mike\node_modules\child_process.jsx doesn't exist
[D:\mike\node_modules\child_process]
[D:\mike\node_modules\child_process]
[D:\mike\node_modules\child_process.js]
[D:\mike\node_modules\child_process.jsx]
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

**Comment by palerdot** [comment]
I think this is something related to your local setup. You can try removing/installing the 'react-d3-speedometer' and try to debug this issue.
