### ISSUE TITLE
Animate 'maxValue' during 'forceRender' when maxValue increases

### ISSUE THREAD

**Issue by pawan-khade** [palerdot/react-d3-speedometer#126]
if forceRender is false then speedometer starts giving problem when value goes beyond max value. Eg. I want to know current users on my website, in that case my initial max value is 100 but using state i have changed it as count increases and goes beyond original 100 max value.

For this I need to enable forceRender. Force render is working fine but for every value change needle goes down then comes up which kind of annoying. 

Can forceRender=false include smooth transitioning of max value also?

**Comment by palerdot** [comment]
> speedometer starts giving problem when value goes beyond max value.
IMHO, this is not the right use case for a speedometer/gauge visualization. Speedometer visualizations are typically used when min/max values are fixed. 

> Can forceRender=false include smooth transitioning of max value also?
This is not the right way to go about wrt UX/visualization perspective. So, this will be not be possible.
