### ISSUE TITLE
Add showing percent value at needle

### ISSUE THREAD

**Issue by ahmadalibaloch** [palerdot/react-d3-speedometer#13]
Showing percentage is required in many use case of a gauge but currently it's not possible to show at what percentage the needle is at.

**Comment by palerdot** [comment]
Can you clarify a bit? You mean the value should read something like `73%` ?

**Comment by ahmadalibaloch** [comment]
Yes. Currently we are showing a value at the base of a needle. I want to show percentage of the arc the needle is pointing at. Look below image, instead of 100 at needle base I want to show percentage (100%). We can also call this feature **custom formatting input for the needle value**.
![percent](https://user-images.githubusercontent.com/1916642/34517472-f80d7aa4-f09c-11e7-925e-688151252a05.png)

**Comment by palerdot** [comment]
Currently formatting value option is not present. I will make this enhancement in the next release. I don't have a specific timeline. Please do watch out this issue for updates.

**Comment by palerdot** [comment]
This feature is added to `v0.2.3` and released. There is a new configuration `currentValueText` which should be provided a string which should have ${value} placeholder which will be replaced with current value. By default, current value is shown (formatted with valueFormat). For example, you need to provide **`${value} %`** to show a percentage after the end of the current value.

You can view a live example - http://palerdot.in/react-d3-speedometer/?selectedKind=react-d3-speedometer&selectedStory=Custom%20Current%20Value%20Text&full=0&down=1&left=1&panelRight=0.You can refer configuration documentation for detailed info - https://github.com/palerdot/react-d3-speedometer#configuration-options.

Make sure you update to `v0.2.3` and use this config for your needs. I'm closing this issue. Please reopen if you find any problems.
