### ISSUE TITLE
Show min and max value labels on speedometer

### ISSUE THREAD

**Issue by iamanoopmk** [palerdot/react-d3-speedometer#15]
I want a single colour speedometer which I achieve by setting the segment as 1. I set the min and max values. But, the max value is not always shown on the speedometer. For example, the following code will show 0 (minValue) and 20 but not the maxValue of 25 on the screen. Is there a way to force the component to show the min and max values on the screen?

``` 
<ReactSpeedometer
    maxValue={25}
    minValue={0}
    value={20}
    needleColor="#5e9da5"
    startColor="#d55b49"
    endColor="#a7abb7"
    ringWidth={10}
    segments={1}
    width={225}/>
```

**Comment by iamanoopmk** [comment]
Currently, I have changed the code where ticks are calculated and set it to an array containing min and max values. Is there any other way to achieve this without changing the library code

**Comment by palerdot** [comment]
> I want a single colour speedometer which I achieve by setting the segment as 1

I think we could simply use a plain arc and no need of a gauge with needle in that scenario. I cannot imagine a situation where a gauge like `react-d3-speedomenter` will be used where the minimum number of segments is less than 2. I think, this library is not suitable for your use case.

**Comment by iamanoopmk** [comment]
Thanks for the reply.
