### ISSUE TITLE
how can i give a unit/prefix/suffix to the segment label value ?

### ISSUE THREAD

**Issue by kennyma-eplus** [palerdot/react-d3-speedometer#151]
i can only format using d3-format 
but can i add some text into it ?

**Comment by palerdot** [comment]
Please use `customSegmentLabels` to have complete control over what data to render - https://github.com/palerdot/react-d3-speedometer#custom-segment-labels---live-example

**Comment by palerdot** [comment]
Please reopen this issue if your case is unique.

**Comment by kennyma-eplus** [comment]
> Please use `customSegmentLabels` to have complete control over what data to render - https://github.com/palerdot/react-d3-speedometer#custom-segment-labels---live-example

@palerdot 
I think `customSegmentLabels` cannot apply 
because i want to add `unit to the `value`,  but not labelling the segment 
![Screenshot 2022-09-26 at 9 31 44 AM](https://user-images.githubusercontent.com/90014814/192177014-4194c16b-28b8-4f03-9119-7f8faad5ac53.png)

For Example, i want to add a "%" after the value
for the `Current Value`, i can use `currentValueText` , but can I add text  to `segment value` ?
