### ISSUE TITLE
how can i give a unit/prefix/suffix to the segment label value ? #151

### ISSUE THREAD

**Issue by kennyma-eplus** [palerdot/react-d3-speedometer#152]
@palerdot  since i have no privileges to re-open the issue, i open a new issue again

#151 

i added comment on it

please take a look

**Comment by palerdot** [comment]
Ok. A `valueFormatter` prop is needed which should take a function and allow user to customize the value like 
```
valueFormatter={value => value + `%`}
```

**Comment by kennyma-eplus** [comment]
yeah, that would be great

**Comment by palerdot** [comment]
`segmentValueFormatter` is introduced to customize segment values. This is available in following versions
- `v.1.1.0`  (`latest`, `React 17`)
- `v2.1.0-rc.0` (`next`, `React 18`)

Reference links
- https://codesandbox.io/s/cool-forest-lv9cxy?file=/src/App.tsx:0-970 (`v2.1.0-rc.0` (`next`, `React 18`))
- https://codesandbox.io/s/charming-bardeen-2j7rin?file=/src/App.tsx (`v.1.1.0`  (`latest`, `React 17`))
- https://palerdot.in/react-d3-speedometer/?path=/story/reactspeedometer--custom-segment-value-formatter

Please reopen this issue in case of any problems.
