### ISSUE TITLE
Upgrade to support react@>=16.0.0

### ISSUE THREAD

**Issue by mkem114** [palerdot/react-d3-speedometer#16]
Could you please verify that it works with a newer react version and update the dependencies with the next release? I don't use all the features but it does _seem_ to work fine.

Thanks for your work otherwise!

**Comment by palerdot** [comment]
Thank you for raising this. I will update this issue once I test all the react dependencies (react, react-dom, react-addons-test-utils) and see if anything is breaking.

**Comment by palerdot** [comment]
I have made a new branch with newest versions of **`React (16)`** and **`Enzyme (3)`**. There are few configuration changes in enzyme test cases but they are passing fine. I will be making this changes mainstream (as **v0.3.0**) once I'm confident of the changes - https://github.com/palerdot/react-d3-speedometer/commit/7ded27c4c2b0e2d37d094185974b1ecea12b0d74, https://travis-ci.org/palerdot/react-d3-speedometer/builds/345599067

**Comment by palerdot** [comment]
React updated to version 16 and the changes are **published** as **v0.3.0** - https://www.npmjs.com/package/react-d3-speedometer. All tests passing and I think this update should be fine.

**Comment by mkem114** [comment]
I have upgraded to 0.3.0 but yarn still gives me the following warning: 
`warning " > react-d3-speedometer@0.3.0" has incorrect peer dependency "react@^0.14.7 || ^15.0.0".`

I believe you may need to update the following in your package.json:
`"peerDependencies": {
    "react": "^0.14.7 || ^15.0.0"
  },`
to:
`"peerDependencies": {
    "react": "^0.14.7 || ^15.0.0 || ^16.0.0"
  },`
or similar (there are no breaking changes until a major version so you could set it to 16.2.0 or everything before 17.0.0)

Thank you for your time.

**Comment by palerdot** [comment]
sure. I have reopened the issue. I will update the peer dependencies and release. I think it is just a warning and will not affect any functionality. Thanks for raising this.

**Comment by palerdot** [comment]
`peerDependencies` updated to **React 16** - https://github.com/palerdot/react-d3-speedometer/commit/41c793f15c3dd314633156a16c1d88c038c2ec93. Released as v0.3.1. I'm closing this issue. Please feel free to reopen if you face any issues. Thank you very much for your help in this issue.
