### ISSUE TITLE
Start and End Color not rendering properly.

### ISSUE THREAD

**Issue by kailashvele** [palerdot/react-d3-speedometer#17]
Expected Start Color: #27ae60
Expected End Color: #e74c3c

But the expected color in the start and end is only seen appropriately when I increase the no of segments. Can it take same colors in less segments as well?

![screen shot 2018-02-22 at 8 36 18 pm](https://user-images.githubusercontent.com/7221983/36545965-28219dca-1810-11e8-8725-99b5c7718abf.png)

**Comment by palerdot** [comment]
Please note that the start and end colors are [interpolated](https://github.com/d3/d3-interpolate). This is the expected behaviour of this library. Please refer the link - https://github.com/d3/d3-interpolate for more details on how color interpolation works.
