### ISSUE TITLE
Tooltip on hover on the segment

### ISSUE THREAD

**Issue by bhaveshkumar96** [palerdot/react-d3-speedometer#174]
is it possible to implement tooltip on hover on any segment of the speedometer gauge chart of yours?? ...if possible can someone please suggest me anything ( any post blog anything will be helpful )
thank you for your valuable time 🙏

Thank you in advance 😁

your help will be appreciated😊

**Comment by palerdot** [comment]
The component has css classes attached to every element of the speedometer (segments `.speedo-segment`, needle `.pointer`, text etc). You can just implement your own tooltip logic with those css classes. Unfortunately, I cannot suggest a specific way to implement for your use cases ... you have to do something like
