### ISSUE TITLE
First value should be equivalent to min value given. Current min value - 1000

### ISSUE THREAD

**Issue by drrviruss** [palerdot/react-d3-speedometer#176]
<img width="434" alt="Screenshot 2023-09-18 171259" src="https://github.com/palerdot/react-d3-speedometer/assets/42537465/8adfaa2c-e931-404f-bf0b-10903a462e77">

no idea whats wrong please help here

**Comment by palerdot** [comment]
I don't understand the problem and expected behaviour. I will not be able to help here.
