### ISSUE TITLE
IE9 throws "SCRIPT1014: Invalid character"

### ISSUE THREAD

**Issue by kzrbill** [palerdot/react-d3-speedometer#18]
IE9 throws "SCRIPT1014: Invalid character", despite page charset being set to UTF-8.

The issue is coming from the \` in the following line 352, index.js: 
return new Function(params, "return \`"+literal+"\`;");

Just needs changing to:
`return new Function(params, "return '"+literal+"';");`

![ie9-script1014-invalid-character](https://user-images.githubusercontent.com/185562/37089704-64b9bda6-21f9-11e8-99eb-3f04b891c5c6.png)

Will raise a pull request to fix.

**Comment by palerdot** [comment]
The library is updated to react 16 which does not support ie9 I guess. If
ie9 support is needed you can stick to 0.2.x version.

**Comment by palerdot** [comment]
Some related discussion here -
https://github.com/facebook/create-react-app/issues/3208

**Comment by palerdot** [comment]
Tests are failing for this fix - https://travis-ci.org/palerdot/react-d3-speedometer/jobs/350274391

But more importantly, IE9 support is officially [dropped](https://www.essent.com/SupportNotices/Blog/Internet-Explorer-9-and-10-Support-Ends-March-31-2017.htm) by Microsoft and it is already marked as expired. 

Also, There is no plan to support IE9. So I'm closing this issue. Thanks for your time in raising this issue and attempting to provide a fix for IE9.

**Comment by palerdot** [comment]
I think your [solution](https://github.com/kzrbill/react-d3-speedometer/commit/84e959f984e5e2a44983f3e6526abd13f6e7ad24) will not add any additional overhead while giving support for IE9. I will be making this change and publishing it in the next version. Thanks for your support in raising this issue and suggesting the fix. Once I'm confident of the changes and when tests are passing I will publish this change.

**Comment by palerdot** [comment]
Tests are passing for this change - https://travis-ci.org/palerdot/react-d3-speedometer/builds/350389569 and I will be releasing this as version for `0.3.2`.

**Comment by palerdot** [comment]
**`0.3.2`** version published with support for IE 9/10/11 by replacing [template string literal](https://caniuse.com/#feat=template-literals) logic with  simple string manipulation. The changes are published as v0.3.2 - https://www.npmjs.com/package/react-d3-speedometer with all tests passing.

Thank you once again for raising this issue and suggesting the fix for supporting IE.

**Comment by kzrbill** [comment]
Great, thanks Arun - that means I can now consume react-d3-speedometer directly. Will attempt to resolve any subsequent issues via pre-tested(!) pull request.
