### ISSUE TITLE
When will v2.0 become general available? is it stable already? 

### ISSUE THREAD

**Issue by ebo-bpi** [palerdot/react-d3-speedometer#181]
Is there anything blocking from moving to v2.0?

**Comment by palerdot** [comment]
It is stable, and it is already used by people in production - https://www.npmjs.com/package/react-d3-speedometer?activeTab=versions

I was just waiting to see if things are causing any issues with v2.0/React18

I will make it generally available in the next few weeks (or hopefully days).

**Comment by palerdot** [comment]
`v2.2.0` released and v2.0 is now generally available - https://www.npmjs.com/package/react-d3-speedometer/v/2.2.0
