### ISSUE TITLE
Can I set maxValue Dynamic

### ISSUE THREAD

**Issue by Prathameshmagdum** [palerdot/react-d3-speedometer#185]
actually,
 im using socket for live value and maxlimit (coming from response ) im setting into maxValue its working good but some data dont have maxlimit so it shows needle in middle of gauge view , now i want to set live value as maxlimit but not working i guess so how can i and also the value is greater than maxlimit that also i want to set as maxlimit how can i 
![Screenshot from 2024-05-01 14-53-17](https://github.com/palerdot/react-d3-speedometer/assets/117511923/e9b1b3ba-2861-4f4d-b0cf-216baaee7833)
![Screenshot from 2024-05-01 15-02-41](https://github.com/palerdot/react-d3-speedometer/assets/117511923/5d26c7d3-279f-4023-b43e-5af9f0bd858b)

**Comment by palerdot** [comment]
I'm not sure if I understand your issue correctly, but you can try the `forceRender` option to rerender the gauge once you change the maxValue dynamically.

**Comment by Prathameshmagdum** [comment]
Okay in response i have maxlimit for particular gauge and that maxlimit i am setting into maxValue now some gauges dont have maxlimit so that time i wants to set the realtime live value coming from socket into maxValue so live value continuously coming at some period of time but its not working, will try forceRender
Thank You !
