### ISSUE TITLE
 any state change affects the needle movement due to force render. Initially, it starts from zero, then updates to the current percentage value upon re-rendering

### ISSUE THREAD

**Issue by SuryaudayMishra** [palerdot/react-d3-speedometer#186]
any state change affects the needle movement due to force render. Initially, it starts from zero, then updates to the current percentage value upon re-rendering

**Comment by daniknewgarden** [comment]
Hey @palerdot!
Have you resolved the issue? Cause at the moment, on version `2.2.1` it still appears. 
I want to achieve the next result, as in the demo gif:
/home/daniel/Videos/Screencasts/Screencast from 2024-07-03 10-02-42.mp4

**Comment by palerdot** [comment]
Please explain the issue in detail, what do you expect to happen and what is happen with a possible stackblitz/codesanbox reproduction. It is difficult to comprehend what you are expecting to happen from the screenshot and issue title. 

PS: `forceRender` option rerenders everything. If you want the need to animate smoothly, do not pass the force render option. Not sure if there is a confusion related to this prop.
