### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by JannikStreek** [palerdot/react-d3-speedometer#20]
Hello,

I am using this library in a project where I need to support IE11. However, due to the missing entry in the .babelrc this is currently not supported and on IE11 the page, where the widget is located, is just broken.

Because this project already has a .babelrc file it is also no option to just transpile it together with the rest of the project. My only remaining solution was to fork this project and adjust the .babelrc file manually:

```
{
  "presets":  [
    [
      "env",
      {
        "targets": {
          "browsers": ["IE 11",
          "> 1%",
          "last 2 versions"]
        }
      }
    ],
    "react-app"
  ],
  "env": {
    "production": {
        "plugins": [
            "transform-remove-console",
            "transform-runtime"
        ],
        "presets": ["babili"]
    }
  }
}
```
(preset es2015 would also be fine)

Happy to create a PR if thats ok. The better approach would be of course - as the todo notes state - to just convert everything to ES2015, should also clear the issue.

**Comment by palerdot** [comment]
Thanks for bringing this to notice. I guess the title should be **Support for IE11** ?

Still I'm little confused. Are you saying the build is not for ES2015 compliant and does not work in IE11. I appreciate pull request. I will think through the consequence and try to bring this change mainstream. thanks

**Comment by JannikStreek** [comment]
Well, I included the module into my react project, but everytime I visited the speedometer with IE11 I got some strange JS error: ```(unknown): ':' expected```. The interesting part is that I have a babel configuration for myself, which should make sure that everything runs smoothly with IE11. But usually you exclude the nodes_modules folder from babel - so this was not helping in this case. And because there is already a .babelrc file in this project it is also not "just enough" to define an exception from the exclude operation for this library, so that the preloader from babel also transpiles this module. The babelrc in this project basically takes precedence over my own babelrc. Therefore the problem.

My guess is that ES2015 could solve that, because IE11 should understand ES2015.

**Comment by palerdot** [comment]
Ok. Because I know people who are using in stuffs like IE9/10 and I have been making minor modifications for those browsers. As far as i know, it should work on browser as low as IE9, but not sure since I use it only on modern browsers. 

Either case let me know.

**Comment by palerdot** [comment]
Not sure if this is relevant. I took the screenshot of this plugin in different browsers using https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots of this [page](http://palerdot.in/react-d3-speedometer/?selectedKind=React%20d3%20Speedometer&selectedStory=Fluid%20Width%20view&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel).

It seems to render in IE11 but not in IE10 and 9. I will try to look into this IE issue. Meanwhile, please share anything relevant wrt to your IE problem
![screen shot 2018-03-13 at 9 14 14 pm](https://user-images.githubusercontent.com/4299398/37352681-d0cdbe98-2703-11e8-9c4d-8e660dbb4c86.png)
![screen shot 2018-03-13 at 9 14 08 pm](https://user-images.githubusercontent.com/4299398/37352683-d10ec794-2703-11e8-9590-d5d7be054fa1.png)

**Comment by palerdot** [comment]
I was able to open the bundle with no problems in IE11. Attached screenshot.

I'm closing this issue. Please reopen if you have more details on this issue.

![sample-ie-capture](https://user-images.githubusercontent.com/4299398/37754040-e06c3942-2dc5-11e8-92c0-ea6a9eb60faa.PNG)
