### ISSUE TITLE
maxValue Does Not Update

### ISSUE THREAD

**Issue by jonow** [palerdot/react-d3-speedometer#22]
I am loading data from a JSON file and If the values for `minValue` or `maxValue` change, this change is not reflected in the gauge. Setting `forceRender` to `true` fixing this issue but also makes the needle reset to its default position making it rapidly swing from 0 to the current value. Is there any way to fix this. Either by making these values update or by making forceRender use an initial value so it does not

**Comment by palerdot** [comment]
This is the preferred behaviour. On update, only the current value is changed and animated as mentioned in the docs. The gauge does not change breaking values like maxValue, minValue, segments etc on update. 

This will be the behaviour of this gauge library and I don't see any configuration changes regarding this.
