### ISSUE TITLE
Giving an invalid needleTransition value does not fail gracefully

### ISSUE THREAD

**Issue by Cin316** [palerdot/react-d3-speedometer#23]
Giving an invalid needTransition value (one that's not of the listed ones from d3-easing-identifiers) does not fail gracefully.  It crashes the whole React app when the speedometer is rendered and does not give an error message.

This is using react-d3-speedometer version 0.3.2.

It produces the error below when it crashes.

<img width="1058" alt="screen shot 2018-08-12 at 8 24 43 pm" src="https://user-images.githubusercontent.com/1988780/44008139-fb6505ee-9e6d-11e8-8d32-6b1060d5ebe3.png">

<img width="1041" alt="screen shot 2018-08-12 at 8 25 02 pm" src="https://user-images.githubusercontent.com/1988780/44008140-fb712b6c-9e6d-11e8-8839-dd50757c0761.png">

**Comment by palerdot** [comment]
Throwing an error in the console and falling back to the default transition should do fine I guess.

**Comment by palerdot** [comment]
This issue is fixed in release `0.3.3` and published. Now, a warning will be thrown in the console if invalid needleTransition is given, and switched to default transition `easeQuadInOut`.
