### ISSUE TITLE
Sample tried in Codesandbox throwing out errors

### ISSUE THREAD

**Issue by JEEVANJGA** [palerdot/react-d3-speedometer#25]
Hi ,
I was just trying out this module in codesandbox, but got stuck with basic implementation itself. need help on what should be done. so that i could develop one sample and use it in other react projects.
https://codesandbox.io/s/mx4nj34y8 .

**Comment by palerdot** [comment]
I made a runnable snippet in [stackblitz](https://stackblitz.com/edit/react-u2bpzm) - https://stackblitz.com/edit/react-u2bpzm. For some reason, the codesandbox snippet is not running, but it is running fine in stackblitz. Please use stackblitz for playing with the component.
