### ISSUE TITLE
How to use mqtt in d3 speedometer using react?

### ISSUE THREAD

**Issue by dhariyalshubham** [palerdot/react-d3-speedometer#29]
I successfully created speedometer but now I want to show real time data using mqtt in it. I have my mqtt but I dont know how to implement it in the speedometer. Anyone here who used it before? Can it be done with d3-speedometer?

**Comment by palerdot** [comment]
Using `react-d3-speedometer` is like any other react component. Not sure of your use case. Closing this as it is not related to this library. Please reopen if you have any `react-d3-speedometer` library specific issues.
