### ISSUE TITLE
textColor input prop is not working

### ISSUE THREAD

**Issue by ahmadalibaloch** [palerdot/react-d3-speedometer#3]
I tried giving color values as 'white', '#fff' and it doesn't change.

**Comment by palerdot** [comment]
Please confirm you are using the latest version of the library. This option was added in `0.1.8` - https://github.com/palerdot/react-d3-speedometer/blob/master/CHANGELOG.md

If you still get this problem in 0.1.8 and above, please let me know.

**Comment by ahmadalibaloch** [comment]
Thanks. Update to 0.1.8 solved it.

**Comment by palerdot** [comment]
Great. I have added an issue for adding a test case for validating `testColor' prop - https://github.com/palerdot/react-d3-speedometer/issues/4
