### ISSUE TITLE
Adding text instead of number

### ISSUE THREAD

**Issue by charan-r** [palerdot/react-d3-speedometer#33]
![speedometer](https://user-images.githubusercontent.com/35986811/48604391-be810b00-e99f-11e8-8ccc-88b7f5d5fc86.png)
can we add text instead of number? Please check the attachment 
Thankyou in advance

**Comment by palerdot** [comment]
This feature is released in `v0.10.0`. [Live Example](https://codesandbox.io/s/vibrant-platform-cesh3)

Documentation - https://palerdot.in/react-d3-speedometer/?path=/story/reactspeedometer--custom-segment-labels

There is a new prop `customSegmentLabels` which will take an array of object with following keys - `text`, `fontSize`, `position (OUTSIDE/INSIDE)`, `color`.

```javascript
// sample code 
   <ReactSpeedometer
      width={500}
      needleHeightRatio={0.7}
      value={777}
      currentValueText="Happiness Level"
      customSegmentLabels={[
        {
          text: "Very Bad",
          position: "INSIDE",
          color: "#555",
        },
        {
          text: "Bad",
          position: "INSIDE",
          color: "#555",
        },
        {
          text: "Ok",
          position: "INSIDE",
          color: "#555",
          fontSize: "19px",
        },
        {
          text: "Good",
          position: "INSIDE",
          color: "#555",
        },
        {
          text: "Very Good",
          position: "INSIDE",
          color: "#555",
        },
      ]}
      ringWidth={47}
      needleTransitionDuration={3333}
      needleTransition="easeElastic"
      needleColor={"#90f2ff"}
      textColor={"#d8dee9"}
```
<img width="597" alt="Screenshot 2020-03-21 at 10 17 30 PM" src="https://user-images.githubusercontent.com/4299398/77244268-29e48800-6c39-11ea-966a-4fdac7074bfc.png">

Please upgrade to `v0.10.0` to use this feature ...
