### ISSUE TITLE
minValue is not showing in speedometer

### ISSUE THREAD

**Issue by Pardeep94** [palerdot/react-d3-speedometer#36]
I am givng minValue but it is not reflect on speedometer.

Here is my code

`<ReactSpeedometer
                        maxValue={500}
                        minValue={100}
                        value={473}
                        needleColor="blue"
                        segments={1}
                        needleTransitionDuration={4000}
                        needleTransition="easeElastic"
                        currentValueText="Current Value: ${value}"
                    />`

![screenshot from 2019-01-09 11-43-52](https://user-images.githubusercontent.com/18335284/50880313-0ce0e200-1404-11e9-890d-faa4e46c494d.png)

**Comment by palerdot** [comment]
I'm not able to reproduce this issue. Please check here - https://stackblitz.com/edit/react-ynxkuv. Please let me know if you can share me a reproducible issue using stackblitz or any other online code editor.
