### ISSUE TITLE
Displaying the Speedometer in wordpress website

### ISSUE THREAD

**Issue by izzycart** [palerdot/react-d3-speedometer#37]
I have been trying to display this package (react-d3-speedometer) on my wordpress page. I installed the package in the plugin folder i created using npm but cant seem to make the speedometer display after adding the following to the page;
```
<div style={{width: "500px",height: "300px",background: "#EFEFEF"}}>
     <ReactSpeedometer />
</div>
```

Please what am i doing wrong or what am i missing?

**Comment by palerdot** [comment]
I'm not sure how a wordpress site renders any react component. This component is meant to be used by `React` apps only.
