### ISSUE TITLE
Splitting into unequal Segments 

### ISSUE THREAD

**Issue by ductuan10081992** [palerdot/react-d3-speedometer#39]
Hello. I want to divide the parts are not equal how will do and the numbers can be decimal?
For example:
Parts 1: 13.5 to 18.4
Parts 2: 18.5 to 24.9
Parts 2: 25 to 29.9
can you help me? thank you very much

**Comment by palerdot** [comment]
@ductuan10081992 
Right now, segments are equally split between min and max values. This feature is **not supported** right now. To accomodate this feature in future also involves lot of logistical changes like getting the values before hand where the split has to happen etc etc. For now, this feature is not supported.

**Comment by swetha2** [comment]
Hello. I want to give a colour till the needle pointer. How do i do that?

**Comment by palerdot** [comment]
This feature is added in `v0.7.0` with a new `customSegmentStops` **configuration/prop**. Please refer - https://palerdot.in/react-d3-speedometer/?path=/story/react-d3-speedometer--custom-segment-stops for reference and for a live example pls check - https://codesandbox.io/s/purple-cdn-eu9xf
