### ISSUE TITLE
segmentColors not including all specified colors.

### ISSUE THREAD

**Issue by masonseeger** [palerdot/react-d3-speedometer#45]
When making a custom color sequence for my speedometer I noticed that the following implementation does not end up showing the light green color for the final segment, but instead shows the blue color twice. I assumed that if there are the same number of segments as there are colors that each color should be represented once. It looks like it is something to do with the d3.scaleQuantize function being used on the segmentColors list. I'll try to do some more digging later, but if you know any more about this problem please let me know!

`

        <ReactSpeedometer
            maxSegmentLabels={12}
            segments={6}
            value={470}
            segmentColors={[
                "#006E0D", //dark green
                "#006E0D",
                "#006E0D",
                "#006E0D",
                "#006e9d", //blueish
                "#0FFE0D" // light green
        ]}
        needleColor="#000080"
      />`

**Comment by palerdot** [comment]
so the way this works is, segments uses [d3-ticks](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks) which will normalise the segments to multiples of `1, 2, 5, 10` ... please read d3 documentation for more details on this ... segmentColors will then be applied to the calculated segments ... This is already mentioned in the README (in the `segments` section) ...
