### ISSUE TITLE
Expected a component class, got [object object]

### ISSUE THREAD

**Issue by satishmane** [palerdot/react-d3-speedometer#5]
<ReactSpeedometer
                    maxValue={500}
                    value={473}
                    needleColor="red"
                    startColor="green"
                    segments={10}
                    endColor="blue"
                />

**Comment by palerdot** [comment]
Can you please share the code you are using ? Also, the package version and node version details are appreciated. thanks

**Comment by palerdot** [comment]
I'm closing this issue now. Please reopen the issue with sample code, library and node versions.
