### ISSUE TITLE
Supporting Negative range like -120 to 0

### ISSUE THREAD

**Issue by sudhir451** [palerdot/react-d3-speedometer#51]
Currently if i want to show the range from -120 to 0, its not working as expected.

In util/index.js 
 calculateSegmentStops  returning the following "  return (current_stop - customSegmentStops[index - 1]) / max "  , Here max is  0 which might be resulting to infinite ,and instead it should be max-min which can fix the issue.

**Comment by palerdot** [comment]
@sudhir451 This issue is fixed and released in `v0.7.1`. Reference sandbox - https://codesandbox.io/s/jolly-thompson-2k3d7 ... Please upgrade to `v0.7.1` which will address this issue. Thanks for raising the issue and suggesting the solution.

**Comment by sudhir451** [comment]
Thanks @palerdot  for the prompt response and resolving the issue.
