### ISSUE TITLE
Setting customSegmentStops does not show correctly

### ISSUE THREAD

**Issue by JerryLMJ** [palerdot/react-d3-speedometer#52]
<img width="198" alt="屏幕快照 2019-09-17 下午7 36 01" src="https://user-images.githubusercontent.com/15794032/65038373-67164780-d982-11e9-8f70-94f97b406ffd.png">
When minValue is not set to 0, the meter is incomplete!

**Comment by JerryLMJ** [comment]
<ReactSpeedometer
                        className="speedometer"
                        needleTransition="easeElastic"
                        needleTransitionDuration={1500}
                        width={150}
                        height={100}
                        ringWidth={20}
                        value={212.46}
                        currentValueText="212.46%"
                        maxValue={300}
                        minValue={90}
                        customSegmentStops={[90, 120, 150, 200, 240, maxValue]}
                        startColor="#FE4819"
                        endColor="#6AD72C"
                        forceRender
                      />

**Comment by sudhir451** [comment]
This issue can be fixed with the solution suggested in issue #51 

![image](https://user-images.githubusercontent.com/1052027/65050003-50dd9c80-d92c-11e9-959a-c53f424129b4.png)

**Comment by palerdot** [comment]
@sudhir451 This issue is fixed and released in `v0.7.1`. Reference sandbox - https://codesandbox.io/s/jolly-thompson-2k3d7 ... Please upgrade to `v0.7.1` which will address this issue. Thanks for bringing attention to this issue ...
