### ISSUE TITLE
Font size and spacings around font

### ISSUE THREAD

**Issue by darren-mayne** [palerdot/react-d3-speedometer#55]
is there a way to increase the font size? (I'm new to react, so pardon if its obvious). When the size of the gauge doubles or larger the font size remains small.

**Comment by palerdot** [comment]
@darren-mayne Right now `fontSize` is not configurable ... I will make it a configurable prop (`fontSize`) and update this issue with details ...

**Comment by palerdot** [comment]
This feature is added in version `0.7.2` ... There are two configurable props - `labelFontSize` and `valueTextFontSize` ... Reference - https://codesandbox.io/s/loving-grass-kbx7f

**Comment by darren-mayne** [comment]
One by product of the change is the space around the edges of the chart only have room for a smaller font. The larger fonts are cut off.

**Comment by palerdot** [comment]
@darren-mayne You are right ... I will see if this can be fixed and update more on this issue ...

**Comment by AndyPSI** [comment]
Bumping this issue as I'm experiencing the same thing @palerdot pointed out. Larger currentValueText font sizes work correctly, but anything larger than default for labelFontSize is clipped.

**Comment by palerdot** [comment]
@AndyPSI I will look into this and try to address this as soon as possible.

**Comment by palerdot** [comment]
To address this issue, two new configurations/props will be introduced `paddingHorizontal`, `paddingVertical`, both of which takes a number (without explicit unit, unit will be taken from `dimensionUnit` config which defaults to `px`). It will look something like the screenshot attached ... I will update this issue once this new configurations are released ... 
<img width="447" alt="Screenshot 2019-11-26 at 10 19 21 PM" src="https://user-images.githubusercontent.com/4299398/69654598-11a19980-109b-11ea-8433-ffa59e96ad41.png">

**Comment by palerdot** [comment]
This issue is addressed in `v0.8.0`. Live Example - https://codesandbox.io/s/blazing-sun-bsm0j

Two new props/configurations have been added `paddingHorizontal`, `paddingVertical` to control the space around the text.

@darren-mayne @AndyPSI Please upgrade to `v0.8.0` (https://www.npmjs.com/package/react-d3-speedometer) and see if it is working as expected. Thanks for your time in pointing out this issue. Please reopen this issue if anything is not working as expected.

**Comment by AndyPSI** [comment]
@palerdot working perfectly, thanks for the quick update!
