### ISSUE TITLE
Expected a component class, got [object object]

### ISSUE THREAD

**Issue by satishmane** [palerdot/react-d3-speedometer#6]
Node version - v7.9.0
"react-d3-speedometer": "0.1.11",

I am facing this issue in react-native mobile app.
[samplecode.txt](https://github.com/palerdot/react-d3-speedometer/files/1266529/samplecode.txt)

render() {
 return (
            <View style={styles.container}>
                    <ReactSpeedometer maxValue={500} value={473} needleColor="red"
                    startColor="green"
                    segments={10}
                    endColor="blue" />
            </View>);
}

**Comment by palerdot** [comment]
From the following code you shared
``` javascript
<View style={styles.container}>
                <ReactSpeedometer
                maxValue={500}
                value={473}
                needleColor="red"
                startColor="green"
                segments={10}
                endColor="blue"
            />
        </View>
```
the problem might be your `style={styles.container}` part, as the `ReactSpeedometer` component looks fine. Can you simply **remove** `ReactSpeedometer` and see if your code works fine?

**Comment by palerdot** [comment]
This component cannot be used in **React Native** as this component uses `ReactDOM` which cannot be used in native mobile environments. Please refer https://stackoverflow.com/questions/37915231/how-to-use-react-j-s-components-in-react-native-app for more info. I'm closing this issue.
