### ISSUE TITLE
Show "%" on the segment values

### ISSUE THREAD

**Issue by yesisiddis** [palerdot/react-d3-speedometer#63]
I'm trying to find out how to add the percentage symbol to the segment values.
I know I can use the "valueFormat" property, but I can't find a way to do it correctly. 
For exemple, if I write valueFormat: ".0%" it will show the label values multiplied by 100.
How can I do it?

Thanks!

**Comment by palerdot** [comment]
You need to work with actual decimal values for plotting in this case. For example like this - https://codesandbox.io/s/strange-cerf-2llsf
```
     <ReactSpeedometer
        minValue={0 / 100}
        maxValue={1000 / 100}
        value={333 / 100}
        valueFormat={".0%"}
      />
```
