### ISSUE TITLE
Getting same color for last 2 segments, even when mentioned otherwise

### ISSUE THREAD

**Issue by meetmangukiya** [palerdot/react-d3-speedometer#68]
Reproducible: https://codesandbox.io/s/modern-darkness-b1jye

**Comment by palerdot** [comment]
This issue is fixed in `v0.10.0` and released. Please update the version and check if it solves the problem. You can check the fix here - https://codesandbox.io/s/gracious-gates-i6bs2

**Comment by meetmangukiya** [comment]
It's fixed, thank you!

**Comment by palerdot** [comment]
Thank you actually for raising this issue ... This is a subtle bug which cannot be reproduced with `3/4/5` segments ... 

Glad that your issue got sorted. Thanks again for bringing this to notice.
