### ISSUE TITLE
unable to resolve module

### ISSUE THREAD

**Issue by satishmane** [palerdot/react-d3-speedometer#7]
I removed node_modules completely and then npm install. I can see react-d3-speedometer in my node_modules, but without src folder in it. At least earlier it used to fail with error "Expected Component, but got class", but now it fails even before that with error unable to resolve module. Can you please let me know reason?

**Comment by palerdot** [comment]
May I know is this related to using `react-d3-speedometer` in **React Native**? As mentioned earlier, this component **cannot** be used in native apps as it uses ReactDOM for all the rendering stuff. For this particular query, I have no idea unless I can look into your dev setup as it is not directly releated to the library api.

**Comment by satishmane** [comment]
Yes, I understand that this component can not be used in react-native. However I want to get to the point where it used to resolve at least dependancy, but used to fail during react-native app launch. Now it is failing even before that. I want to fork this project and play with it to make it compatible for react-native
