### ISSUE TITLE
Removing @babel/runtime-corejs2 dependency

### ISSUE THREAD

**Issue by rosczja** [palerdot/react-d3-speedometer#76]
This library depends on @babel/runtime and @babel/runtime-corejs2. The second dependency prevents upgrading our application to corejs3.

As far as I understand the babel configuration, the second dependency is not needed, because the configuration of the plugin @babel/plugin-transform-runtime has set the option "corejs" to "false".

Can the dependency @babel/runtime-corejs2 be removed?

**Comment by palerdot** [comment]
@rosczja Thanks for pointing this out. `@babel/runtime-corejs2` is a stale dependency. I guess you are right that this dependency should be removed.

I will remove `@babel/runtime-corejs2` as dependency and release as `v0.12.0`.

I will update this issue once done.

**Comment by palerdot** [comment]
@rosczja `@babel/runtime-corejs2` dependency is removed and released in [`v0.12.0`](https://www.npmjs.com/package/react-d3-speedometer/v/0.12.0)

Please reopen in case you run into any trouble regarding this.

**Comment by rosczja** [comment]
Thanks a lot.
