### ISSUE TITLE
unable to resolve dependancy

### ISSUE THREAD

**Issue by satishmane** [palerdot/react-d3-speedometer#8]
Yes, I understand that this component can not be used in react-native. However I want to get to the point where it used to resolve at least dependancy, but used to fail during react-native app launch. Now it is failing even before that. I want to fork this project and play with it to make it compatible for react-native

**Comment by palerdot** [comment]
I cannot help you with this issue as it seems something related with your local setup. You are free to fork this and port it to react native, but I cannot help regarding your local setup. I'm closing this issue.
