### ISSUE TITLE
Use react-d3-speedometer with Nextjs

### ISSUE THREAD

**Issue by mingbackmountain** [palerdot/react-d3-speedometer#84]
![test](https://user-images.githubusercontent.com/25886138/91941303-36f6be80-ed23-11ea-9bbd-cdd1dfdfb7b5.PNG)

I keep getting this error when I apply the compent to my Nextjs project. Can somebody help me with this problem?

**Comment by palerdot** [comment]
Please reopen this issue with more details if you still have problems integrating with `nextjs`
