### ISSUE TITLE
SSR not possible due to `lodash-es`

### ISSUE THREAD

**Issue by shariffy** [palerdot/react-d3-speedometer#89]
Hi,

After having successfully used this package in a standard `react` setting, I was trying to port that code to `next.js` to enable some Server-Side rendering, when the following error was thrown:
```
[...]/node_modules/lodash-es/isNumber.js:1
import baseGetTag from './_baseGetTag.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([...]/node_modules/react-d3-speedometer/dist/core/util/index.js:1:616)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

It appears from the Changelog that normal `lodash` was replaced not that long ago, without significant changes since, so I was able to downgrade to `0.10.1` without much issue but thought I'd post a shout as an FYI, for future design consideration, or other people running into this.

**Comment by palerdot** [comment]
@shariffy It is possible to make this library work with `nextjs`. Please refer this issue for more details - https://github.com/palerdot/react-d3-speedometer/issues/84 ... In short, you need to use [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) so that *nextjs understands es6 exports* ... 

Please feel free to reopen if you think you still can't integrate with nextjs. I will add this information as FAQ in README

**Comment by palerdot** [comment]
I have updated the title to `[Resolved]` so that future visitors would have more context from the title itself. Please feel free to reopen in case you run into any troubles integrating with `next.js`

**Comment by Fensterbank** [comment]
I don't get it work with Next 10.

Tried it like this 

_next.config.js_
```javascript
const withTM = require('next-transpile-modules')(['lodash-es']);

module.exports = withTM({});
```

But the issue persists.
Why don't you just use lodash, which supports tree shaking? I read a lot about that you don't need lodash-es anymore but only for this library I have to somehow need to get it work. :(

**Comment by palerdot** [comment]
Sample `next.config.js` to make this work

```javascript
const withTM = require("next-transpile-modules")([
  "lodash-es",
  "react-d3-speedometer"
]);

module.exports = withTM();
```

sample code sandbox - https://codesandbox.io/s/serene-worker-h094e?file=/next.config.js:0-123

**Comment by warmansuganda** [comment]
hi @palerdot i've other solution for next.js, it works for me!

```js
import React from 'react';
import dynamic from 'next/dynamic';

const ReactSpeedometer = dynamic(
  () => import('react-d3-speedometer'),
  { ssr: false },
);

function Speedometer() {
  return (
    <div>
      <ReactSpeedometer />
    </div>
  );
}

export default GrafikTimbangan;
```

**Comment by palerdot** [comment]
@warmansuganda Thank you. I will link this issue in the FAQ so that people can find the solution you suggested. 

You can also raise a PR for this if you are interested.
