### ISSUE TITLE
Rerender on new width/height

### ISSUE THREAD

**Issue by AvoJFB** [palerdot/react-d3-speedometer#9]
I'm trying to rerender component on resize so I'm storing window's width and height in parent's state and passing them to ReactSpeedometer Component via props. It's getting new props but it doesn't rerender

**Comment by palerdot** [comment]
Is it possible to have some kind of fiddle for this issue? I will try to reproduce this, but it would be better if you can make a JSFiddle or something similar. Thanks.

**Comment by palerdot** [comment]
Or you can reproduce your code snippet here. Ideally, if you are passing the width/height as props and if it changes, it should rerender with new value.

```javascript
<ParentElement>
  <ReactSpeedometer
     width={this.state.width}
     height={this.state.height}
  />
</ParentElement>
```
Is your code something similar to above? I will try to reproduce the same, if you can share your code snippet. Thanks.

**Comment by AvoJFB** [comment]
![image](https://user-images.githubusercontent.com/20437842/31118628-bb4436f2-a836-11e7-9d66-37b91287efaf.png)
Here's the code. If I check it in React devtools I see that new props are passing but the component doesn't rerender.
(If u wanna copy the code - https://jsfiddle.net/3dcxp6cj/ )

**Comment by palerdot** [comment]
Thanks. I will take a peek into this issue.

**Comment by palerdot** [comment]
You are right. Right now, the speedometer will update/animate only if the needle value changes. This was the intended behaviour because it made sense just to animate the change in the needle values. 

If we rerender fully, then there comes a question of how to handle the appearance changes, since the whole speedometer appearance might change (like color, segements etc).

Let me think over this issue and will try to come up with a solution.

**Comment by palerdot** [comment]
I'm planning to add a new configuration `forceRender` which will **default to false**. By giving true to this prop, the speedometer component should rerender the whole component. It is better to have it as a configuration, as it allows better control for people to customise for their use case.

In your use case, you can achieve this like this

```javascript
<ParentElement>
  <ReactSpeedometer
     width={this.state.width}
     height={this.state.height}
     forceRender={true}
  />
</ParentElement>
```
I still believe once mounted/initialized, animating only the needle values will lead to smooth visualization. So, I'm planning to have the existing behaviour as default.

Let me know your feedback on this.

**Comment by AvoJFB** [comment]
Yeah I think that is a good idea. Also you can add configuration for debounce, like if for last 0.5 seconds there're no new props then rerender component. But make this equal to 0 by default. Because when resizing, dimensions are changing very fast so maybe someone want to debounce it.

**Comment by palerdot** [comment]
This config param is added to version `0.2.0` and released - https://github.com/palerdot/react-d3-speedometer/releases/tag/v0.2.0 

Test cases are also added for this config. Now with `forceRender` config, one can override the default behaviour and force render the whole component on props change.

**Comment by AvoJFB** [comment]
Thank you very much!

**Comment by palerdot** [comment]
Thanks for raising this issue. Let me know if everything goes well for you after updating to version `0.2.0`

**Comment by AvoJFB** [comment]
Yeah, everything is ok. We were using this speedometer for showing fidget spinner's speed :D

**Comment by jeghers** [comment]
Ok hours of trying to get this to resize properly in a resizable dashboard panel... just wont work.  In the React debugger in Chrome, I see the proper width and height being applied to the component and it still is the wrong size and randomly positioned wrong.  I tried and tried, but sorry, I must move on to another component.

**Comment by Amanjadon2023** [comment]
force render works well thanks for this it helps me

**Comment by Amanjadon2023** [comment]
now resize event  works well using force render={true}

**Comment by SuryaudayMishra** [comment]
In this what is happening any state changes it impacts the needle movement as it goes from zero and then goes to current percentage value
